/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PostRouteImport } from './routes/post'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as IdeaIdeaIdRouteImport } from './routes/idea.$ideaId'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdeaIdRoute = IdeaIdeaIdRouteImport.update({
  id: '/idea/$ideaId',
  path: '/idea/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/people': typeof PeopleRoute
  '/post': typeof PostRoute
  '/signup': typeof SignupRoute
  '/idea/$ideaId': typeof IdeaIdeaIdRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/people': typeof PeopleRoute
  '/post': typeof PostRoute
  '/signup': typeof SignupRoute
  '/idea/$ideaId': typeof IdeaIdeaIdRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/people': typeof PeopleRoute
  '/post': typeof PostRoute
  '/signup': typeof SignupRoute
  '/idea/$ideaId': typeof IdeaIdeaIdRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/login'
    | '/onboarding'
    | '/people'
    | '/post'
    | '/signup'
    | '/idea/$ideaId'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/onboarding'
    | '/people'
    | '/post'
    | '/signup'
    | '/idea/$ideaId'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/login'
    | '/onboarding'
    | '/people'
    | '/post'
    | '/signup'
    | '/idea/$ideaId'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PeopleRoute: typeof PeopleRoute
  PostRoute: typeof PostRoute
  SignupRoute: typeof SignupRoute
  IdeaIdeaIdRoute: typeof IdeaIdeaIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$ideaId': {
      id: '/idea/$ideaId'
      path: '/idea/$ideaId'
      fullPath: '/idea/$ideaId'
      preLoaderRoute: typeof IdeaIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PeopleRoute: PeopleRoute,
  PostRoute: PostRoute,
  SignupRoute: SignupRoute,
  IdeaIdeaIdRoute: IdeaIdeaIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
